#FLEXPRET_ROOT_DIR ?= ../../../../../flexpret
#NAME ?= riscv-gt
#APP_SOURCES ?= ../../../test/test_flexpret_simulator/programs/add/addgt/riscv-gt.o
#vpath %.riscv
#include $(FLEXPRET_ROOT_DIR)/Makefrag

#FLEXPRET_ROOT_DIR ?= ..
#NAME ?= main
#APP_SOURCES ?= .
#include $(FLEXPRET_ROOT_DIR)/Makefrag

FLEXPRET_ROOT_DIR = ../../../../../../../flexpret
NAME = riscv-gt
APP_SOURCES = riscv-gt.o
include $(FLEXPRET_ROOT_DIR)/Makefrag