FLEXPRET_ROOT_DIR ?= ..
NAME ?= main
APP_SOURCES ?= .
include $(FLEXPRET_ROOT_DIR)/Makefrag

# example:
#FLEXPRET_ROOT_DIR = ../../../flexpret
#NAME = riscv-gt
#APP_SOURCES = riscv-gt.o
#include $(FLEXPRET_ROOT_DIR)/Makefrag